
name: update backlink

on:
  workflow_dispatch:  # Trigger manually
  # schedule:
    # - cron: "0 */12 * * *"

jobs:
  scrape-app-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Ensure your required version is used

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install httpx google-play-scraper aiohttp aiohttp_socks bs4 DataRecorder pandas DrissionPage python-dotenv app_store_scraper requests tqdm waybackpy cdx_toolkit lxml
      - name: Run scraper and save results
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_D1_DATABASE_ID: ${{ secrets.D1_APP_DATABASE_ID }}    
          RESULT_FOLDER: ./result  # Adjust if necessary
          OUTPUT_FOLDER: ./output
          
        run: |
          python domainMonitor.py
      - name: upload files          
        uses: actions/upload-artifact@v4
        with:
            name: healthapps
            path: ./result/ # or path/to/artifact
